In [1]:
import pandas as pd
import numpy as np

In [2]:
#load movies and ratings

movies = pd.read_csv('Data/movies_sml.csv')
ratings = pd.read_csv('Data/ratings_sml.csv')

In [3]:
# load movies with bag of words. Needed for content filtering

movies_bow = pd.read_csv('Data/movies_bow.csv')

In [4]:
#load ratings matrix.Needed for Collaborative filtering
ratings_matrix = pd.read_hdf('Data/ratings_mx.h5')

In [5]:
# load predictions
preds = pd.read_hdf('Data/preds_hdf2.h5')

###### test collab system first to see if any additional files are needed

In [6]:


def recommend_movies(predictions, userId, movies, original_ratings, num_recommendations):
    
    # Get and sort the user's predictions
    user_row_number = userId - 1 # User ID starts at 1, not 0
    sorted_user_predictions = preds.iloc[user_row_number].sort_values(ascending=False) # User ID starts at 1
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings[original_ratings.userId == (userId)]
    user_full = (user_data.merge(movies, how = 'left', left_on = 'movieId', right_on = 'movieId').
                     sort_values(['rating'], ascending=False)
                 )

#     print (f"User {0} has already rated {1} movies. format(userID, user_full.shape[0]")
#     print 'Recommending highest {0} predicted ratings movies not already rated.'.format(num_recommendations)
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies[~movies['movieId'].isin(user_full['movieId'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'movieId',
               right_on = 'movieId').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )
    rec_movies = recommendations['Title']
    already_rated = user_full['Title_x']
    return  already_rated, rec_movies

In [7]:
already_rated, predictions = recommend_movies(preds, 60, movies, ratings, 20)

In [8]:
predictions

423                       Schindler's List
215     Star Wars: Episode IV - A New Hope
293                           Forrest Gump
102                             Braveheart
6587                             Inception
6003                                    Up
5575                                WALL·E
1420                     Life Is Beautiful
1950                             Gladiator
8495                          Interstellar
249                 Léon: The Professional
485                                  Fargo
3110                          Finding Nemo
7820                      Django Unchained
8928                    The Imitation Game
5957                  Inglourious Basterds
5748                   Slumdog Millionaire
5059                           Ratatouille
2950                   Catch Me If You Can
9237                            Inside Out
Name: Title, dtype: object

###### test content system first to see if any additional files are needed

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
# Initializing and generating the count matrix 

count = CountVectorizer()
count_matrix = count.fit_transform(movies_bow['bag_of_words'])

In [11]:
# Generating the cosine similarity matrix

cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [12]:
#map index to Title. This will be used in the function and is integral to 
# how we access the recommended movies

indices = pd.Series(movies_bow.index, index = movies_bow['Title'])

#Create recommendation function

def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:26]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return movies_bow['Title'].iloc[movie_indices]

In [13]:
get_recommendations('Rumble in the Bronx')

11663                   Kung Fu Yoga
4129                       Who Am I?
3463                     Crime Story
670                       Supercop 2
690      Around the World in 80 Days
691      Around the World in 80 Days
1143                       Mr. Magoo
1416                       Rush Hour
1595                      Black Mask
2008                   Shanghai Noon
2440                     Rush Hour 2
4071                     City Hunter
4976                     Thunderbolt
5320                     Rush Hour 3
9890                    Dragon Blade
11352                      Skiptrace
11463                Railroad Tigers
1226                    Mr. Nice Guy
3052                Shanghai Knights
4397                        Gorgeous
4649                New Police Story
6441               Shinjuku Incident
6894              Little Big Soldier
4974                    Swordsman II
0                          Toy Story
Name: Title, dtype: object

#### Combine Systems

In [31]:
# already loaded
# indices = pd.Series(movies_bow.index, index = movies_bow['Title'])

indices

Title
Toy Story                                                       0
Jumanji                                                         1
Grumpier Old Men                                                2
Waiting to Exhale                                               3
Father of the Bride Part II                                     4
Heat                                                            5
Heat                                                            6
Sabrina                                                         7
Sabrina                                                         8
Tom and Huck                                                    9
Sudden Death                                                   10
GoldenEye                                                      11
Dracula: Dead and Loving It                                    12
Balto                                                          13
Nixon                                                          14
Cutthroat Island                                               15
Casino                                                         16
Sense and Sensibility                                          17
Four Rooms                                                     18
Ace Ventura: When Nature Calls                                 19
Money Train                                                    20
Get Shorty                                                     21
Copycat                                                        22
Assassins                                                      23
Powder                                                         24
Leaving Las Vegas                                              25
Othello                                                        26
Othello                                                        27
Now and Then                                                   28
Persuasion                                                     29
                                                            ...
Cru                                                         11978
The Emoji Movie                                             11979
The Saint                                                   11980
Dragstrip Girl                                              11981
Dying to Belong                                             11982
Eating                                                      11983
Getting Out                                                 11984
Hit Me                                                      11985
How to Be Louise                                            11986
Aiyyaa                                                      11987
The Nile Hilton Incident                                    11988
Zygote                                                      11989
Girls Trip                                                  11990
Landline                                                    11991
Rick and Morty: State of Georgia Vs. Denver Fenton Allen    11992
A German Life                                               11993
Cure for Pain: The Mark Sandman Story                       11994
Ducoboo                                                     11995
First Kill                                                  11996
Descendants 2                                               11997
Little Girls in Pretty Boxes                                11998
Scribe                                                      11999
Over/Under                                                  12000
The Visitors: Bastille Day                                  12001
Monster Ark                                                 12002
High Plains Invaders                                        12003
Headless Horseman                                           12004
Kuka                                                        12005
In a Heartbeat                                              12006
Century of Birthing                                         12007
Length: 12008, dtype: int64

In [32]:
idx = indices['Jumanji']

In [36]:
sim_scores = list(enumerate(cosine_sim[idx]))

In [37]:
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

In [38]:
sim_scores = sim_scores[1:26]

In [39]:
movie_indices = [i[0] for i in sim_scores]

In [73]:
content_results = pd.DataFrame(movies_bow['movieId'].iloc[movie_indices])


content_results

      movieId
120       137
121     48593
412       500
601       765
1120     1702
1409     2253
1430     2297
1483     2431
1520     2501
1635     2718
1646     2759
1700     2882
1785     3105
1807     3156
1942     3489
2102     3882
2348     4372
2723     5334
2732     5349
2801     5528
3108     6285
3489     7154
3565     7324
3824     8636
3895     8866

In [75]:
# get user predictions

user_row_number = 60 # User ID starts at 1, not 0

sorted_user_predictions = pd.DataFrame(preds.iloc[user_row_number].sort_values(ascending=False))

sorted_user_predictions.head()

               60
movieId
296      5.001825
2858     4.363025
608      3.931749
1193     3.701406
778      3.509410

In [91]:
# Get the movies the user originally rated
user_data = ratings[ratings.userId == user_row_number]

#combine the movies the user originally rated with the movies dataset and only keeping the movies
#the user rated

user_full = (user_data.merge(movies, how = 'left', left_on = 'movieId', right_on = 'movieId').
                     sort_values(['rating'], ascending=False))

In [93]:
print(user_full.columns)

user_full = user_full[['userId', 'movieId', 'Title_x', 'rating', 'genres', 'Actors', 'Director', 'Plot', 'Poster']].rename(columns = {'Title_x': 'Title'})


user_full.head()

Index(['userId', 'movieId', 'Title_x', 'rating', 'genres', 'Actors',
       'Director', 'Plot', 'Poster'],
      dtype='object')

,userId,movieId,Title,rating,genres,Actors,Director,Plot,Poster
0,60,4878,Donnie Darko,5.0,Drama|Mystery|Sci-Fi|Thriller,"Jake Gyllenhaal, Holmes Osborne, Maggie Gyllen...",Richard Kelly,A troubled teenager is plagued by visions of a...,https://m.media-amazon.com/images/M/MV5BZjZlZD...
52,60,8957,Saw,5.0,Horror|Mystery|Thriller,"Leigh Whannell, Cary Elwes, Danny Glover, Ken ...",James Wan,"Two strangers, who awaken in a room with no re...",https://m.media-amazon.com/images/M/MV5BMjE4MD...
32,60,714,Dead Man,5.0,Drama|Mystery|Western,"Johnny Depp, Gary Farmer, Crispin Glover, Lanc...",Jim Jarmusch,"On the run after murdering a man, accountant W...",https://m.media-amazon.com/images/M/MV5BYTJlZm...
33,60,1466,Donnie Brasco,5.0,Crime|Drama,"Al Pacino, Johnny Depp, Michael Madsen, Bruno ...",Mike Newell,An FBI undercover agent infiltrates the mob an...,https://m.media-amazon.com/images/M/MV5BYzMzMD...
22,60,2329,American History X,5.0,Crime|Drama,"Edward Norton, Edward Furlong, Beverly D'Angel...",Tony Kaye,A former neo-nazi skinhead tries to prevent hi...,https://m.media-amazon.com/images/M/MV5BZjA0MT...

(70, 9)

In [77]:
num_recommendations = 50

## TOM, I need to figure this section out

Need to convert the original code to fit into the hybrid. I was trying to work around the missing Predictions column without having to create extra dataframes. In cell 102, I think I'm making a basic mistake with my merge. 

The last cell below shows the results using the original code in cell 78. The issue is I can't sort it without the prediction scores. I need the outcome from cell 78 below to include the prediction scores.

In [78]:
# Original Code from Collaborative Filter Function

# Recommend the highest predicted rating movies that the user hasn't seen yet.
movie_preds = (movies[~movies['movieId'].isin(user_full['movieId'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'movieId',
               right_on = 'movieId').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
)

# join the predictions and the movies the user rated, removing the ones already rated from th

In [102]:
preds_test = pd.merge(sorted_user_predictions, user_full, how='left',
            left_on= 'movieId', right_on='movieId')
# .rename(columns = {user_row_number: 'Predictions'})

#             sort_values('Predictions', ascending = False).
#                        iloc[:num_recommendations, :-1]
preds_test

,movieId,60,userId,Title,rating,genres,Actors,Director,Plot,Poster
0,296,5.001825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2858,4.363025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,608,3.931749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1193,3.701406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,778,3.509410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2997,3.317179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7361,2.735573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6016,2.589245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2959,2.500412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3949,2.479702,60.0,Requiem for a Dream,5.0,Drama,"Ellen Burstyn, Jared Leto, Jennifer Connelly, ...",Darren Aronofsky,The drug-induced utopias of four Coney Island ...,https://m.media-amazon.com/images/M/MV5BOTdiNz...
10,6711,2.133206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5618,2.095416,60.0,Spirited Away,5.0,Adventure|Animation|Fantasy,"Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takash...","Hayao Miyazaki, Kirk Wise","During her family's move to the suburbs, a sul...",https://m.media-amazon.com/images/M/MV5BOGJjNz...
12,1089,2.073814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2692,1.925374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,4226,1.792981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,4848,1.749213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4878,1.738010,60.0,Donnie Darko,5.0,Drama|Mystery|Sci-Fi|Thriller,"Jake Gyllenhaal, Holmes Osborne, Maggie Gyllen...",Richard Kelly,A troubled teenager is plagued by visions of a...,https://m.media-amazon.com/images/M/MV5BZjZlZD...
17,2324,1.676436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,55820,1.581866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3160,1.499952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2329,1.458594,60.0,American History X,5.0,Crime|Drama,"Edward Norton, Edward Furlong, Beverly D'Angel...",Tony Kaye,A former neo-nazi skinhead tries to prevent hi...,https://m.media-amazon.com/images/M/MV5BZjA0MT...
21,3000,1.373289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4235,1.264868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1175,1.236340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1213,1.235138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1921,1.073628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2712,1.058665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,48394,1.049556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1884,1.036983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,356,1.026400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
11978,49272,-0.356454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11979,34162,-0.359060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11980,71535,-0.366386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11981,6539,-0.370462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11982,122886,-0.370490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11983,3916,-0.391230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11984,112852,-0.398253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11985,1265,-0.399163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11986,1923,-0.399619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11987,134853,-0.410065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11988,115617,-0.429616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11989,1721,-0.441960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11990,377,-0.449031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11991,2502,-0.449615,60.0,Office Space,4.0,Comedy|Crime,"Ron Livingston, Jennifer Aniston, David Herman...",Mike Judge,Three company workers who hate their jobs deci...,https://m.media-amazon.com/images/M/MV5BOTA5Mz...
11992,3897,-0.459333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11993,122904,-0.464897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11994,1407,-0.474841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11995,349,-0.504520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11996,4022,-0.510601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11997,59315,-0.514209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11998,3948,-0.552078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11999,4886,-0.555053,60.0,"Monsters, Inc.",3.0,Adventure|Animation|Children|Comedy|Fantasy,"John Goodman, Billy Crystal, Mary Gibbs, Steve...","Pete Docter, David Silverman(co-director), Lee...","In order to power the city, monsters have to s...",https://m.media-amazon.com/images/M/MV5BMTY1NT...
12000,553,-0.589505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12001,3578,-0.654670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12002,161,-0.668648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12003,1259,-0.685539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12004,474,-0.719807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12005,39,-0.722616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12006,33794,-0.735197,60.0,Batman Begins,4.5,Action|Crime|IMAX,"Christian Bale, Michael Caine, Liam Neeson, Ka...",Christopher Nolan,"After training with his mentor, Batman begins ...",https://m.media-amazon.com/images/M/MV5BZmUwNG...
12007,1393,-0.801624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
movie_preds.shape

(50, 7)

In [52]:
# lookup movie predictions from content system from this dataframe

movie_recs = pd.merge(content_results, movie_preds, how='left', left_on='movieId', right_on='movieId').
    sort_values()

,movieId,Title,genres,Actors,Director,Plot,Poster
250,296,Pulp Fiction,Comedy|Crime|Drama|Thriller,"Tim Roth, Amanda Plummer, Laura Lovelace, John...",Quentin Tarantino,"The lives of two mob hitmen, a boxer, a gangst...",https://m.media-amazon.com/images/M/MV5BNGNhMD...
1658,2858,American Beauty,Drama|Romance,"Kevin Spacey, Annette Bening, Thora Birch, Wes...",Sam Mendes,A sexually frustrated suburban father has a mi...,https://m.media-amazon.com/images/M/MV5BNTBmZW...
485,608,Fargo,Comedy|Crime|Drama|Thriller,"William H. Macy, Steve Buscemi, Peter Stormare...","Joel Coen, Ethan Coen",Jerry Lundegaard's inept crime falls apart due...,https://m.media-amazon.com/images/M/MV5BNDJiZD...
799,1193,One Flew Over the Cuckoo's Nest,Drama,"Jack Nicholson, Louise Fletcher, Will Sampson,...",Milos Forman,A criminal pleads insanity after getting into ...,https://m.media-amazon.com/images/M/MV5BZjA0OW...
597,778,Trainspotting,Comedy|Crime|Drama,"Ewan McGregor, Ewen Bremner, Jonny Lee Miller,...",Danny Boyle,"Renton, deeply immersed in the Edinburgh drug ...",https://m.media-amazon.com/images/M/MV5BMzA5Zj...
1714,2997,Being John Malkovich,Comedy|Drama|Fantasy,"John Cusack, Cameron Diaz, Ned Bellamy, Eric W...",Spike Jonze,A puppeteer discovers a portal that leads lite...,https://m.media-amazon.com/images/M/MV5BYmUxY2...
3530,7361,Eternal Sunshine of the Spotless Mind,Drama|Romance|Sci-Fi,"Jim Carrey, Kate Winslet, Gerry Robert Byrne, ...",Michel Gondry,"When their relationship turns sour, a couple u...",https://m.media-amazon.com/images/M/MV5BMTY4Nz...
2967,6016,City of God,Action|Adventure|Crime|Drama|Thriller,"Alexandre Rodrigues, Leandro Firmino, Phellipe...","Fernando Meirelles, Kátia Lund(co-director)","In the slums of Rio, two kids' paths diverge a...",https://m.media-amazon.com/images/M/MV5BMGU5OW...
1698,2959,Fight Club,Action|Crime|Drama|Thriller,"Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier",David Fincher,An insomniac office worker and a devil-may-car...,https://m.media-amazon.com/images/M/MV5BMjJmYT...
3254,6711,Lost in Translation,Comedy|Drama|Romance,"Scarlett Johansson, Bill Murray, Akiko Takeshi...",Sofia Coppola,A faded movie star and a neglected young woman...,https://m.media-amazon.com/images/M/MV5BMTI2ND...
754,1089,Reservoir Dogs,Crime|Mystery|Thriller,"Harvey Keitel, Tim Roth, Michael Madsen, Chris...",Quentin Tarantino,When a simple jewelry heist goes horribly wron...,https://m.media-amazon.com/images/M/MV5BZmExNm...
1588,2692,Run Lola Run,Action|Crime,"Franka Potente, Moritz Bleibtreu, Herbert Knau...",Tom Tykwer,"After a botched money delivery, Lola has 20 mi...",https://m.media-amazon.com/images/M/MV5BMmU5Zj...
2234,4226,Memento,Mystery|Thriller,"Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, ...",Christopher Nolan,A man with short-term memory loss attempts to ...,https://m.media-amazon.com/images/M/MV5BZTcyNj...
2466,4848,Mulholland Drive,Crime|Drama|Film-Noir|Mystery|Thriller,"Naomi Watts, Jeanne Bates, Dan Birnbaum, Laura...",David Lynch,After a car wreck on the winding Mulholland Dr...,https://m.media-amazon.com/images/M/MV5BNWM2MD...
1420,2324,Life Is Beautiful,Comedy|Drama|Romance|War,"Roberto Benigni, Nicoletta Braschi, Giorgio Ca...",Roberto Benigni,When an open-minded Jewish librarian and his s...,https://m.media-amazon.com/images/M/MV5BYmJmM2...
5338,55820,No Country for Old Men,Crime|Drama,"Tommy Lee Jones, Javier Bardem, Josh Brolin, W...","Ethan Coen, Joel Coen",Violence and mayhem ensue after a hunter stumb...,https://m.media-amazon.com/images/M/MV5BMjA5Nj...
1779,3160,Magnolia,Drama,"Pat Healy, Genevieve Zweig, Mark Flanagan, Nei...",Paul Thomas Anderson,An epic mosaic of interrelated characters in s...,https://m.media-amazon.com/images/M/MV5BZjk3YT...
1717,3000,Princess Mononoke,Action|Adventure|Animation|Drama|Fantasy,"Billy Crudup, Billy Bob Thornton, Minnie Drive...",Hayao Miyazaki,On a journey to find the cure for a Tatarigami...,https://m.media-amazon.com/images/M/MV5BMTVlNW...
2242,4235,Amores Perros,Drama|Thriller,"Emilio Echevarría, Gael García Bernal, Goya To...",Alejandro G. Iñárritu,A horrific car accident connects three stories...,https://m.media-amazon.com/images/M/MV5BMWJhOT...
790,1175,Delicatessen,Comedy|Drama|Romance,"Pascal Benezech, Dominique Pinon, Marie-Laure ...","Marc Caro, Jean-Pierre Jeunet",Post-apocalyptic surrealist black comedy about...,https://m.media-amazon.com/images/M/MV5BNjg5ZD...
802,1213,Goodfellas,Crime|Drama,"Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...",Martin Scorsese,The story of Henry Hill and his life in the mo...,https://m.media-amazon.com/images/M/MV5BY2NkZj...
1262,1921,Pi,Drama|Sci-Fi|Thriller,"Sean Gullette, Mark Margolis, Ben Shenkman, Pa...",Darren Aronofsky,A paranoid mathematician searches for a key nu...,https://m.media-amazon.com/images/M/MV5BMjYzNT...
1600,2712,Eyes Wide Shut,Drama|Mystery|Thriller,"Tom Cruise, Nicole Kidman, Madison Eginton, Ja...",Stanley Kubrick,"A New York City doctor embarks on a harrowing,...",https://m.media-amazon.com/images/M/MV5BMjA5NT...
4947,48394,Pan's Labyrinth,Drama|Fantasy|Thriller,"Ivana Baquero, Sergi López, Maribel Verdú, Dou...",Guillermo del Toro,"In the Falangist Spain of 1944, the bookish yo...",https://m.media-amazon.com/images/M/MV5BMTU3OD...
1232,1884,Fear and Loathing in Las Vegas,Adventure|Comedy|Drama,"Johnny Depp, Benicio Del Toro, Tobey Maguire, ...",Terry Gilliam,An oddball journalist and his psychopathic law...,https://m.media-amazon.com/images/M/MV5BNjA2ZD...
293,356,Forrest Gump,Comedy|Drama|Romance|War,"Tom Hanks, Rebecca Williams, Sally Field, Mich...",Robert Zemeckis,"The presidencies of Kennedy and Johnson, the e...",https://m.media-amazon.com/images/M/MV5BNWIwOD...
2821,5669,Bowling for Columbine,Documentary,"Michael Moore, Salvador Allende, Jacobo Arbenz...",Michael Moore,Filmmaker Michael Moore explores the roots of ...,https://m.media-amazon.com/images/M/MV5BOWY2OW...
5393,56782,There Will Be Blood,Drama|Western,"Daniel Day-Lewis, Martin Stringer, Matthew Bra...",Paul Thomas Anderson,"A story of family, religion, hatred, oil and m...",https://m.media-amazon.com/images/M/MV5BMjAxOD...
260,306,Three Colors: Red,Drama,"Irène Jacob, Jean-Louis Trintignant, Frédériqu...",Krzysztof Kieslowski,A model discovers her neighbor is keen on inva...,https://m.media-amazon.com/images/M/MV5BYTg1Mm...
261,307,Three Colors: Blue,Drama,"Juliette Binoche, Benoît Régent, Florence Pern...",Krzysztof Kieslowski,A woman struggles to find a way to live her li...,https://m.media-amazon.com/images/M/MV5BZGJhND...
576,741,Ghost in the Shell,Animation|Sci-Fi,"Scarlett Johansson, Pilou Asbæk, Takeshi Kitan...",Rupert Sanders,"In the near future, Major Mira Killian is the ...",https://m.media-amazon.com/images/M/MV5BMzJiNT...
800,1203,12 Angry Men,Drama,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",Sidney Lumet,A jury holdout attempts to prevent a miscarria...,https://m.media-amazon.com/images/M/MV5BMWU4N2...
4867,46578,Little Miss Sunshine,Adventure|Comedy|Drama,"Abigail Breslin, Greg Kinnear, Paul Dano, Alan...","Jonathan Dayton, Valerie Faris",A family determined to get their young daughte...,https://m.media-amazon.com/images/M/MV5BMTgzNT...
3352,6953,21 Grams,Crime|Drama|Mystery|Romance|Thriller,"Sean Penn, Naomi Watts, Danny Huston, Carly Nahon",Alejandro G. Iñárritu,A freak accident brings together a critically ...,https://m.media-amazon.com/images/M/MV5BMjA4Mj...
1123,1729,Jackie Brown,Crime|Drama|Thriller,"Pam Grier, Samuel L. Jackson, Robert Forster, ...",Quentin Tarantino,A middle-aged woman finds herself in the middl...,https://m.media-amazon.com/images/M/MV5BNmY5OD...
817,1274,Akira,Action|Adventure|Animation|Sci-Fi,"Mitsuo Iwata, Nozomu Sasaki, Mami Koyama, Tess...",Katsuhiro Ôtomo,A secret military project endangers Neo-Tokyo ...,https://m.media-amazon.com/images/M/MV5BM2ZiZT...
5293,55247,Into the Wild,Action|Adventure|Drama,"Emile Hirsch, Marcia Gay Harden, William Hurt,...",Sean Penn,"After graduating from Emory University, top st...",https://m.media-amazon.com/images/M/MV5BMTAwND...
4330,31658,Howl's Moving Castle,Adventure|Animation|Fantasy|Romance,"Chieko Baishô, Takuya Kimura, Akihiro Miwa, Ta...",Hayao Miyazaki,When an unconfident young woman is cursed with...,https://m.media-amazon.com/images/M/MV5BZTRhY2...
2898,5878,Talk to Her,Drama|Romance,"Javier Cámara, Darío Grandinetti, Leonor Watli...",Pedro Almodóvar,Two men share an odd friendship while they car...,https://m.media-amazon.com/images/M/MV5BMzBlND...
4271,30749,Hotel Rwanda,Drama|War,"Don Cheadle, Xolani Mali, Desmond Dube, Hakeem...",Terry George,Paul Rusesabagina was a hotel manager who hous...,https://m.media-amazon.com/images/M/MV5BZGJjYm...
1752,3083,All About My Mother,Drama,"Cecilia Roth, Marisa Paredes, Candela Peña, An...",Pedro Almodóvar,Young Esteban wants to become a writer and als...,https://m.media-amazon.com/images/M/MV5BZTk2ZT...
804,1219,Psycho,Crime|Horror,"Anthony Perkins, Vera Miles, John Gavin, Janet...",Alfred Hitchcock,A Phoenix secretary embezzles forty thousand d...,https://m.media-amazon.com/images/M/MV5BNTQwND...
4308,31410,Downfall,Drama|War,"Bruno Ganz, Alexandra Maria Lara, Corinna Harf...",Oliver Hirschbiegel,"Traudl Junge, the final secretary for Adolf Hi...",https://m.media-amazon.com/images/M/MV5BZDFmNz...
5961,68237,Moon,Drama|Mystery|Sci-Fi|Thriller,"Sam Rockwell, Kevin Spacey, Dominique McElligo...",Duncan Jones,Astronaut Sam Bell has a quintessentially pers...,https://m.media-amazon.com/images/M/MV5BMTgzOD...
3538,7371,Dogville,Drama|Mystery|Thriller,"Nicole Kidman, Harriet Andersson, Lauren Bacal...",Lars von Trier,A woman on the run from the mob is reluctantly...,https://m.media-amazon.com/images/M/MV5BMTkwNT...
6587,79132,Inception,Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",Christopher Nolan,A thief who steals corporate secrets through t...,https://m.media-amazon.com/images/M/MV5BMjAxMz...
3431,7147,Big Fish,Drama|Fantasy|Romance,"Ewan McGregor, Albert Finney, Billy Crudup, Je...",Tim Burton,A frustrated son tries to determine the fact f...,https://m.media-amazon.com/images/M/MV5BMTYyMz...
262,308,Three Colors: White,Comedy|Drama,"Zbigniew Zamachowski, Julie Delpy, Janusz Gajo...",Krzysztof Kieslowski,"After his wife divorces him, a Polish immigran...",https://m.media-amazon.com/images/M/MV5BNTliYT...
1288,2010,Metropolis,Drama|Sci-Fi,"Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rog...",Fritz Lang,In a futuristic city sharply divided between t...,https://m.media-amazon.com/images/M/MV5BMTg5YW...
3313,6870,Mystic River,Crime|Drama|Mystery,"Sean Penn, Tim Robbins, Kevin Bacon, Laurence ...",Clint Eastwood,The lives of three men who were childhood frie...,https://m.media-amazon.com/images/M/MV5BMTIzND...